import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#f5f7ff',
  '--slot4-page-text': '#16244f',
  '--slot4-panel-bg': '#eef3ff',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#5d6e9f',
  '--slot4-soft-muted-text': '#7f90bb',
  '--slot4-accent': '#d51c39',
  '--slot4-accent-fill': '#0f78db',
  '--slot4-accent-soft': 'rgba(15,120,219,0.12)',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#202d63',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#dfe7ff',
  '--slot4-cream': '#ffffff',
  '--slot4-warm': '#f4f8ff',
  '--slot4-lavender': '#eff3ff',
  '--slot4-gray': '#ebf0ff',
  '--slot4-body-gradient': 'linear-gradient(180deg,#f7f8ff 0%,#f1f5ff 100%)',
  '--editable-page-bg': '#f5f7ff',
  '--editable-page-text': '#16244f',
  '--editable-container': '1540px',
  '--editable-border': 'rgba(27,63,131,0.12)',
  '--editable-nav-bg': 'rgba(25,41,98,0.94)',
  '--editable-nav-text': '#f5f8ff',
  '--editable-nav-active': '#feec41',
  '--editable-nav-active-text': '#16244f',
  '--editable-cta-bg': '#0f78db',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': 'rgba(255,255,255,0.12)',
  '--editable-footer-bg': '#243160',
  '--editable-footer-text': '#f8fbff',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_18px_50px_rgba(21,45,104,0.1)]',
  shadowStrong: 'shadow-[0_28px_80px_rgba(10,25,72,0.24)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(22,36,79,0.04),rgba(22,36,79,0.78))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-16 sm:py-20 lg:py-24',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[220px] shrink-0 snap-start sm:w-[260px]',
  },
  type: {
    eyebrow: 'text-[11px] font-bold uppercase tracking-[0.28em] text-[var(--slot4-accent-fill)]',
    heroTitle: 'text-4xl font-semibold leading-[0.96] tracking-[-0.04em] sm:text-5xl lg:text-[4.5rem]',
    sectionTitle: 'text-3xl font-semibold tracking-[-0.03em] sm:text-4xl lg:text-[3.3rem]',
    body: 'text-base leading-8',
  },
  surface: {
    card: `rounded-[1.75rem] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[1.75rem] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[1.9rem] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-7 py-3.5 text-sm font-bold uppercase tracking-[0.12em] text-[var(--slot4-on-accent)] transition duration-200 hover:translate-y-[-1px] hover:brightness-95 active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-white/35 bg-white/10 px-7 py-3.5 text-sm font-bold uppercase tracking-[0.12em] text-white transition duration-200 hover:bg-white/18 active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent)] px-7 py-3.5 text-sm font-bold uppercase tracking-[0.12em] text-[var(--slot4-on-accent)] transition duration-200 hover:translate-y-[-1px] hover:brightness-95 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-[1.6rem] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[4/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1.5 hover:shadow-[0_24px_60px_rgba(16,41,98,0.18)]',
    fade: 'transition duration-300 hover:opacity-85',
  },
} as const

export const aiLayoutRules = [
  'Keep the large blue-to-magenta hero and editorial white sections as the main visual rhythm.',
  'Use only src/editable/** and preserve all route-facing props and exports.',
  'Keep multiple card styles active across the home and task archive surfaces.',
  'Prefer generous spacing, rounded panels, and premium serif headlines with clean sans body copy.',
  'Render all post media and summaries defensively with fallbacks.',
  'Use postHref() for post links so task routes keep working.',
] as const
